
package com.gzedu.xlims.common.wcf.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IAPPDataSynchService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
	com.gzedu.xlims.common.wcf.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
	com.gzedu.xlims.common.wcf.org.tempuri.ObjectFactory.class
})
public interface IAPPDataSynchService {


    /**
     * 
     * @param dataSynchResult
     * @param outMSG
     * @param synchDATA
     * @param functionType
     * @param operatingUserName
     * @param key
     */
    @WebMethod(operationName = "DataSynch", action = "http://tempuri.org/IAPPDataSynchService/DataSynch")
    @RequestWrapper(localName = "DataSynch", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DataSynch")
    @ResponseWrapper(localName = "DataSynchResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DataSynchResponse")
    public void dataSynch(
        @WebParam(name = "operatingUserName", targetNamespace = "http://tempuri.org/")
        String operatingUserName,
        @WebParam(name = "functionType", targetNamespace = "http://tempuri.org/")
        String functionType,
        @WebParam(name = "key", targetNamespace = "http://tempuri.org/")
        String key,
        @WebParam(name = "synchDATA", targetNamespace = "http://tempuri.org/")
        String synchDATA,
        @WebParam(name = "DataSynchResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> dataSynchResult,
        @WebParam(name = "outMSG", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> outMSG);

}
